#tiger_hunt_homepage:
#    path:     /
#    defaults: { _controller: TigerHuntBundle:Default:index }

get_task_list:
  path: /tasks
  defaults: { _controller: TigerHuntBundle:TaskList:getTaskList}
  methods: [POST]

submit_task_list:
  path: /tasks/submit
  defaults: { _controller: TigerHuntBundle:TaskList:submitTaskItem }
  methods: [POST]
