get_task_list:
  path: /tasks
  defaults: { _controller: TigerHuntBundle:TaskList:getTaskList}
  methods: [GET]

submit_task_list:
  path: /tasks/submit
  defaults: { _controller: TigerHuntBundle:TaskList:submitTaskItem }
  methods: [POST]

view_api_calls:
  path: /api-documentation
  defaults: {_controller: TigerHuntBundle:API:index }
