services:

  # controller
  tiger_hunt.abstract_controller:
    class: TigerHuntBundle\Controller\AbstractController
    abstract: true
    calls:
      - [setLogger, ["@logger"]]

  tiger_hunt.api_controller:
    class: TigerHuntBundle\Controller\APIController

# repository classes




